name: Lint

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:

concurrency:
  group: "lint ${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint-cspell:
    name: Lint CSpell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**"
          config: .cspell.json
          strict: true
          verbose: true

  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pdm install

      - name: Code Style Check
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"

      - name: Code Lint
        run: pylint src/

      - name: Type Check
        run: mypy src/
